/** Product/service suggestions for the invoice line datalist. */
export const INVOICE_PRODUCT_SUGGESTIONS: string[] = [
  "1st Surveillance Audit (10.5 hrs)",
  "2nd Surveillance Audit On Site Audit (10.5 hrs)",
  "Adjustment",
  "Adjustment done to tally balance versus quickbook and cash on hand",
  "Annual Accreditation Fee",
  "HSE Program Assessment",
  "ISO Application Fee",
  "ISO Initial Assessment",
  "Safety Culture Assessment",
  "Audit Planning and Report Preparation (3hrs)",
  "BFAT Training",
  "BLS Orientation",
  "BOSH ID Card",
  "Basic English",
  "Basic Firefighting Training",
  "Basic First Aid",
  "Basic Safety Training",
  "Behavioral Based Safety",
  "Borrowed Cash",
  "Business Communications Training",
  "COSH Certificate",
  "Civil Service Review- CSC",
  "Confine Space plus Permit to Work",
  "Confined Space",
  "Confined Space Training",
  "Confined Space and Gas Testing Training",
  "HSE Internship for Oil and Gas (240-hr)",
  "Consultancy & Certification",
  "HSE Internship for Oil and Gas (600-hr)",
  "HSE Internship Program for Oil and Gas",
  "Creation of Safety Culture Program",
  "Consultancy",
  "Program Deployment",
  "Provisions of DOLE Accredited Safety Consultant",
  "Site Visit",
  "EMS NCII",
  "EMS NCII Assessment",
  "Emergency Medical Response Training",
  "Emergency Medical Services NC II Assessment",
  "Emergency firts Aide Training",
  "Equipment Purchase",
  "Sales of Asset",
  "Fixed Asset Account",
  "Flora Assessment",
  "HIRAC- Hazard Identification, Risk Assessment, and Control",
  "HSE",
  "HSE Competency Assessment",
  "HSE Consultancy",
  "5S Training",
  "HSE Training",
  "Basic Occupational Safety and Health (BOSH) for Safety Officer 1",
  "Basic Occupational Safety and Health (BOSH) for Safety Officer 2",
  "Construction Occupational Safety and Health (COSH) Training",
  "Occupational First Aid",
  "Safety Program Audit",
  "Safety Services",
  "Hours",
  "Human Resource Seminar",
  "IOSH Managing Safely and OSHA Based General Training",
  "International Occupational Safety and health",
  "Intravenous Therapy Training ( IVT)",
  "LCM",
  "Late payment charge",
  "5% late payment charge on outstanding balance",
  "Leadership Skills for Supervisors – Communication, Coaching",
  "Lock Out Tag out",
  "Lock Out Tag out (LOTO) plus Electrical Safety",
  "Loss Control Management Training",
  "Loss Cosh Id fee",
  "Lost Certificate Replacement Fee",
  "MESH - Mandatory Eight - Hour safety and Health .",
  "Meal allowance",
  "COSH Completion ID",
  "Merchandise",
  "Training Manual",
  "OSH Awareness",
  "OTHER Expense",
  "Occupational First Aid Training SFAT",
  "Office Expense",
  "Paypal Transaction Charge",
  "Product Safety management Training",
  "Referral fee",
  "Refund",
  "IELTS",
  "Review",
  "Sales",
  "Scaffolding Safety Training",
  "Drug-Free Workplace Seminar",
  "Seminar",
  "OSH Awareness, Disaster Risk Management Awareness and Basic CPR Training",
  "Occupational Safety & Security for Hotel/Resort Industry",
  "Seminar on Occupational Safety & Security for Hotel",
  "Shipping Fee",
  "Soft Skills Training",
  "Stage 1 On-Site Audit (8hrs)",
  "Stage 2 Certification Audit - On-site Audit (16 hours)",
  "Training Expense",
  "Training Supplies",
  "Training food expense",
  "ACLS Training",
  "Training",
  "Autocad Training",
  "BLS",
  "BLS/ACLS Package",
  "Basic Electrical Safety Training",
  "Corporate Team Building Training",
  "HSE Internal Audit Training",
  "IADC RigPass",
  "IADC HSE Rigpass Training",
  "IADC RigPass - Regular",
  "Identification Card",
  "Loss Cosh Id",
  "OSHA",
  "PECB ISO 27001 LEAD IMPLPEMENTER",
  "PECB ISO 27001 Lead Implementer",
  "Print PVC Id",
  "WAH- Work at Heights",
  "Utilities",
  "Utility",
  "VAT",
  "Waste Control Safety Training",
  "Withholding Tax",
  "Working at Heights plus Heavy Equipment Safety",
  "Working at heights Training",
  "courier Fee",
  "fare expense",
  "well control",
  "Assessment",
];
